name: advent_code_playground
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dev_dependencies:
  very_good_analysis: ^3.1.0
dependencies:
  collection: ^1.17.0
