name: flutter_spotify_ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  desktop_window: ^0.4.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.2.0
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0
  graphql: ^5.1.3
  hooks_riverpod: ^2.2.0
  json_annotation: ^4.8.0
  riverpod_annotation: ^1.2.1
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.2.5
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  riverpod_generator: ^1.2.0
  riverpod_lint: ^1.0.1
  very_good_analysis: ^4.0.0+1

flutter_gen:
  output: lib/

flutter:
  uses-material-design: true
  assets:
    - asset/image/
    - asset/logo/
  fonts:
    - family: Montserrat
      fonts:
        - asset: font/Montserrat-Regular.ttf
          weight: 400
        - asset: font/Montserrat-Medium.ttf
          weight: 500
        - asset: font/Montserrat-SemiBold.ttf
          weight: 600
        - asset: font/Montserrat-Bold.ttf
          weight: 700
