name: pub_riverpod_code_gen
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_svg: ^2.0.0+1
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.1.3
  html: ^0.15.1
  json_annotation: ^4.8.0
  pubspec_parse: ^1.2.1
  riverpod_annotation: ^1.1.1
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  riverpod_generator: ^1.1.1
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - asset/