module.exports = {
    libraries: [
        { id: 1, title: 'Made For You' },
        { id: 2, title: 'Recently Played' },
        { id: 3, title: 'Liked Songs' },
        { id: 4, title: 'Albums' },
        { id: 5, title: 'Artists' },
        { id: 6, title: 'Podcasts' }
    ],
    playlists: [
        {
            id: 1,
            name: 'Today\'s Top Hits',
            imageURL: '',
            description: '',
            creator: 'Various Artists',
            duration: '28 min',
            followers: '0',
        },
        {
            id: 2,
            name: 'Discover Weekly',
            imageURL: '',
            description: '',
            creator: 'Various Artists',
            duration: '28 min',
            followers: '0',
        },
        {
            id: 3,
            name: 'Release Radar',
            imageURL: '',
            description: '',
            creator: 'Various Artists',
            duration: '28 min',
            followers: '0',
        },
        {
            id: 4,
            name: 'Chill',
            imageURL: '',
            description: '',
            creator: 'Various Artists',
            duration: '28 min',
            followers: '0',
        },
        {
            id: 5,
            name: 'Background',
            imageURL: '',
            description: '',
            creator: 'Various Artists',
            duration: '28 min',
            followers: '0',
        },
        {
            id: 6,
            name: 'lofi hip hop music - beats to relax/study to',
            imageURL: 'assets/lofigirl.jpg',
            description: 'A daily selection of chill beats - perfect to help you relax & study 📚',
            creator: 'Lofi Girl',
            duration: '28 min',
            followers: '5,351,685',
        },
        {
            id: 7,
            name: 'Vibes Right Now',
            imageURL: '',
            description: '',
            creator: 'Various Artists',
            duration: '28 min',
            followers: '0',
        },
        {
            id: 8,
            name: 'Time Capsule',
            imageURL: '',
            description: '',
            creator: 'Various Artists',
            duration: '28 min',
            followers: '0',
        },
        {
            id: 9,
            name: 'On Repeat',
            imageURL: '',
            description: '',
            creator: 'Various Artists',
            duration: '28 min',
            followers: '0',
        },
        {
            id: 10,
            name: 'Summer Rewind',
            imageURL: '',
            description: '',
            creator: 'Various Artists',
            duration: '28 min',
            followers: '0',
        },
        {
            id: 11,
            name: 'Dank Doggo Tunes',
            imageURL: '',
            description: '',
            creator: 'Various Artists',
            duration: '28 min',
            followers: '0',
        },
        {
            id: 12,
            name: 'Sleepy Doge',
            imageURL: '',
            description: '',
            creator: 'Various Artists',
            duration: '28 min',
            followers: '0',
        },

    ],
    songs: [
        {
            id: 1,
            title: 'Snowman',
            artist: 'WYS',
            album: '1 Am. Study Session',
            duration: '3:15',
        },
        {
            id: 2,
            title: 'Healthy Distraction',
            artist: 'less.people',
            album: 'One Day It\'s Over',
            duration: '2:18',
        },
        {
            id: 3,
            title: 'Far Away',
            artist: 'Mila Coolness',
            album: 'Silent River',
            duration: '2:39',
        },
        {
            id: 4,
            title: 'Call You Soon',
            artist: 'Louk, Glimlip',
            album: 'Can We Talk',
            duration: '2:35',
        },
        {
            id: 5,
            title: 'Winter Sun',
            artist: 'Bcalm, Banks',
            album: 'Feelings',
            duration: '2:15',
        },
        {
            id: 6,
            title: 'Hope',
            artist: 'No Spirit',
            album: 'Memories We Made',
            duration: '1:57',
        },
        {
            id: 7,
            title: 'A Better Place',
            artist: 'Project AER, cxit.',
            album: 'Growth Patterns',
            duration: '2:00',
        },
        {
            id: 8,
            title: 'Misty Dawn',
            artist: 'BluntOne',
            album: 'Autumn in Budapest',
            duration: '2:34',
        },
        {
            id: 9,
            title: 'Hourglass',
            artist: 'Thaehan',
            album: 'Hourglass',
            duration: '1:43',
        },
        {
            id: 10,
            title: 'After Sunset',
            artist: 'Project AER, WYS',
            album: '3 Am. Study Session',
            duration: '2:41',
        },
        {
            id: 11,
            title: 'Child',
            artist: 'Ambulo',
            album: 'Polar',
            duration: '2:12',
        },
        {
            id: 12,
            title: 'Arizona Zero',
            artist: 'WYS, Sweet Medicine',
            album: 'Evermore',
            duration: '2:31',
        }
    ],
    playlistsSongs: [
        {
            id: 1,
            song_id: 1,
            playlist_id: 6,
        },
        {
            id: 1,
            song_id: 2,
            playlist_id: 6,
        },
        {
            id: 3,
            song_id: 3,
            playlist_id: 6,
        },
        {
            id: 4,
            song_id: 4,
            playlist_id: 6,
        },
        {
            id: 5,
            song_id: 5,
            playlist_id: 6,
        },
        {
            id: 6,
            song_id: 6,
            playlist_id: 6,
        },
        {
            id: 7,
            song_id: 7,
            playlist_id: 6,
        },
        {
            id: 8,
            song_id: 8,
            playlist_id: 6,
        },
        {
            id: 9,
            song_id: 9,
            playlist_id: 6,
        },
        {
            id: 10,
            song_id: 10,
            playlist_id: 6,
        },
        {
            id: 11,
            song_id: 11,
            playlist_id: 6,
        },
        {
            id: 12,
            song_id: 12,
            playlist_id: 6,
        },
    ],

}