name: riverpod_error_handler
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  freezed_annotation: ^2.2.0
  graphql: ^5.1.2
  hooks_riverpod: ^2.2.0
  json_annotation: ^4.8.0
  riverpod_annotation: ^1.2.1

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.2.5
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^1.2.0
  riverpod_lint: ^1.0.1
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
