name: open_meteo_api
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  dio: ^4.0.6
  meta: ^1.8.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.22.0
  very_good_analysis: ^3.1.0
